// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RGSkin.Bindings
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "rgskin";





        [DllImport(__DllName, EntryPoint = "fromOsu", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void fromOsu(byte* input_dir, byte* output_dir);


    }



}
