// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RGSkin.Bindings
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "rgskin";





        [DllImport(__DllName, EntryPoint = "fromOsu", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool fromOsu(byte* input_dir, byte* skin_output_dir, [MarshalAs(UnmanagedType.U1)] bool export_layout, byte* layout_output_dir, byte** error_out);

        [DllImport(__DllName, EntryPoint = "free_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_error(byte* ptr);


    }



}
